package actions

import (
	"fmt"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/DappPocket/easy_chain_lennon/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Transaction)
// DB Table: Plural (transactions)
// Resource: Plural (Transactions)
// Path: Plural (/transactions)
// View Template Folder: Plural (/templates/transactions/)

// TransactionsResource is the resource for the Transaction model
type TransactionsResource struct {
	buffalo.Resource
}

// List gets all Transactions. This function is mapped to the path
// GET /transactions
func (v TransactionsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	transactions := &models.Transactions{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Transactions from the DB
	if err := q.Where("hide = ?", false).Order("timestamp DESC").All(transactions); err != nil {
		return err
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, transactions))
}

// Show gets the data for one Transaction. This function is mapped to
// the path GET /transactions/{transaction_id}
func (v TransactionsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	// To find the Transaction the parameter transaction_id is used.
	if err := tx.Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, transaction))
}

// New renders the form for creating a new Transaction.
// This function is mapped to the path GET /transactions/new
func (v TransactionsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Transaction{}))
}

// Create adds a Transaction to the DB. This function is mapped to the
// path POST /transactions
func (v TransactionsResource) Create(c buffalo.Context) error {
	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	// Bind transaction to the html form elements
	if err := c.Bind(transaction); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(transaction)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, transaction))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "transaction.created.success"))
	// and redirect to the transactions index page
	return c.Render(201, r.Auto(c, transaction))
}

// Edit renders a edit form for a Transaction. This function is
// mapped to the path GET /transactions/{transaction_id}/edit
func (v TransactionsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	if err := tx.Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, transaction))
}

// Update changes a Transaction in the DB. This function is mapped to
// the path PUT /transactions/{transaction_id}
func (v TransactionsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	if err := tx.Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Transaction to the html form elements
	if err := c.Bind(transaction); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(transaction)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, transaction))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "transaction.updated.success"))
	// and redirect to the transactions index page
	return c.Render(200, r.Auto(c, transaction))
}

// Destroy deletes a Transaction from the DB. This function is mapped
// to the path DELETE /transactions/{transaction_id}
func (v TransactionsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	// To find the Transaction the parameter transaction_id is used.
	if err := tx.Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(transaction); err != nil {
		return err
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "transaction.destroyed.success"))
	// Redirect to the transactions index page
	return c.Render(200, r.Auto(c, transaction))
}
